version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        # AMQP protocol port
        - 5672:5672
        # HTTP management UI
        - 15672:15672